name: CD Pipeline BE

on:
  workflow_run:
    workflows:
      - CI Pipeline BE
    types:
      - completed

jobs:
  deploy-orders-service:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS CLI
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: us-east-1

      - name: Set Default Environment
        id: set-environment
        run: |
          echo "Setting environment..."
          if [[ -z "${{ github.event.inputs.environment }}" ]]; then
            echo "Environment not provided. Defaulting to 'dev'."
            echo "ENVIRONMENT=dev" >> $GITHUB_ENV
          else
            echo "ENVIRONMENT=${{ github.event.inputs.environment }}" >> $GITHUB_ENV
          fi    

      - name: Debug Inputs
        run: echo "Environment:${{ github.event.inputs.environment }}"


      - name: Set Cluster Name Based on Environment
        id: set-cluster
        run: |
          if [[ "${{ github.event.inputs.environment }}" == "main" ]]; then
            echo "CLUSTER_NAME=${{ secrets.CLUSTER_NAME_MAIN }}" >> $GITHUB_ENV
          elif [[ "${{ github.event.inputs.environment }}" == "test" ]]; then
            echo "CLUSTER_NAME=${{ secrets.CLUSTER_NAME_TEST }}" >> $GITHUB_ENV
          else
            echo "CLUSTER_NAME=${{ secrets.CLUSTER_NAME_DEV }}" >> $GITHUB_ENV
          fi



      - name: Authenticate with EKS
        run: aws eks update-kubeconfig --region us-east-1 --name ${{ env.CLUSTER_NAME }}

      - name: Deploy Orders Service
        run: kubectl apply -f k8s/orders-service-deployment.yaml

  deploy-payments-service:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS CLI
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: us-east-1

      - name: Set Default Environment
        id: set-environment
        run: |
          echo "Setting environment..."
          if [[ -z "${{ github.event.inputs.environment }}" ]]; then
            echo "Environment not provided. Defaulting to 'dev'."
            echo "ENVIRONMENT=dev" >> $GITHUB_ENV
          else
            echo "ENVIRONMENT=${{ github.event.inputs.environment }}" >> $GITHUB_ENV
          fi    

      - name: Debug Inputs
        run: echo "Environment:${{ github.event.inputs.environment }}"

      - name: Set Cluster Name Based on Environment
        id: set-cluster
        run: |
          if [[ "${{ github.event.inputs.environment }}" == "main" ]]; then
            echo "CLUSTER_NAME=${{ secrets.CLUSTER_NAME_MAIN }}" >> $GITHUB_ENV
          elif [[ "${{ github.event.inputs.environment }}" == "test" ]]; then
            echo "CLUSTER_NAME=${{ secrets.CLUSTER_NAME_TEST }}" >> $GITHUB_ENV
          else
            echo "CLUSTER_NAME=${{ secrets.CLUSTER_NAME_DEV }}" >> $GITHUB_ENV
          fi
          
      - name: Authenticate with EKS
        run: aws eks update-kubeconfig --region us-east-1 --name ${{ env.CLUSTER_NAME }}

      - name: Deploy Payments Service
        run: kubectl apply -f k8s/payments-service-deployment.yaml

  deploy-products-service:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS CLI
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: us-east-1
          
      - name: Set Default Environment
        id: set-environment
        run: |
          echo "Setting environment..."
          if [[ -z "${{ github.event.inputs.environment }}" ]]; then
            echo "Environment not provided. Defaulting to 'dev'."
            echo "ENVIRONMENT=dev" >> $GITHUB_ENV
          else
            echo "ENVIRONMENT=${{ github.event.inputs.environment }}" >> $GITHUB_ENV
          fi
          
      - name: Debug Inputs
        run: echo "Environment:${{ github.event.inputs.environment }}"

      - name: Set Cluster Name Based on Environment
        id: set-cluster
        run: |
          if [[ "${{ github.event.inputs.environment }}" == "main" ]]; then
            echo "CLUSTER_NAME=${{ secrets.CLUSTER_NAME_MAIN }}" >> $GITHUB_ENV
          elif [[ "${{ github.event.inputs.environment }}" == "test" ]]; then
            echo "CLUSTER_NAME=${{ secrets.CLUSTER_NAME_TEST }}" >> $GITHUB_ENV
          else
            echo "CLUSTER_NAME=${{ secrets.CLUSTER_NAME_DEV }}" >> $GITHUB_ENV
          fi
          
      - name: Authenticate with EKS
        run: aws eks update-kubeconfig --region us-east-1 --name ${{ env.CLUSTER_NAME }}

      - name: Deploy Products Service
        run: kubectl apply -f k8s/products-service-deployment.yaml

  deploy-shipping-service:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS CLI
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: us-east-1

      - name: Set Default Environment
        id: set-environment
        run: |
          echo "Setting environment..."
          if [[ -z "${{ github.event.inputs.environment }}" ]]; then
            echo "Environment not provided. Defaulting to 'dev'."
            echo "ENVIRONMENT=dev" >> $GITHUB_ENV
          else
            echo "ENVIRONMENT=${{ github.event.inputs.environment }}" >> $GITHUB_ENV
          fi

      - name: Debug Inputs
        run: echo "Environment:${{ github.event.inputs.environment }}"

      - name: Set Cluster Name Based on Environment
        id: set-cluster
        run: |
          if [[ "${{ github.event.inputs.environment }}" == "main" ]]; then
            echo "CLUSTER_NAME=${{ secrets.CLUSTER_NAME_MAIN }}" >> $GITHUB_ENV
          elif [[ "${{ github.event.inputs.environment }}" == "test" ]]; then
            echo "CLUSTER_NAME=${{ secrets.CLUSTER_NAME_TEST }}" >> $GITHUB_ENV
          else
            echo "CLUSTER_NAME=${{ secrets.CLUSTER_NAME_DEV }}" >> $GITHUB_ENV
          fi
          
      - name: Authenticate with EKS
        run: aws eks update-kubeconfig --region us-east-1 --name ${{ env.CLUSTER_NAME }}

      - name: Deploy Shipping Service
        run: kubectl apply -f k8s/shipping-service-deployment.yaml
