name: Deploy to EKS

on:
  workflow_dispatch:

jobs:
  deploy-orders-service:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS CLI
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: us-east-1

      - name: Get Cluster Name
        id: get-cluster-name
        run: echo "CLUSTER_NAME=$(terraform output eks_cluster_name)" >> $GITHUB_ENV

      - name: Authenticate with EKS
        run: aws eks update-kubeconfig --region us-east-1 --name ${{ env.CLUSTER_NAME }}

      - name: Deploy Orders Service
        run: kubectl apply -f k8s/orders-service-deployment.yaml

  deploy-payments-service:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS CLI
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: us-east-1

      - name: Get Cluster Name
        id: get-cluster-name
        run: echo "CLUSTER_NAME=$(terraform output eks_cluster_name)" >> $GITHUB_ENV

      - name: Authenticate with EKS
        run: aws eks update-kubeconfig --region us-east-1 --name ${{ env.CLUSTER_NAME }}

      - name: Deploy Payments Service
        run: kubectl apply -f k8s/payments-service-deployment.yaml

  deploy-products-service:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS CLI
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: us-east-1

      - name: Get Cluster Name
        id: get-cluster-name
        run: echo "CLUSTER_NAME=$(terraform output eks_cluster_name)" >> $GITHUB_ENV

      - name: Authenticate with EKS
        run: aws eks update-kubeconfig --region us-east-1 --name ${{ env.CLUSTER_NAME }}

      - name: Deploy Products Service
        run: kubectl apply -f k8s/products-service-deployment.yaml

  deploy-shipping-service:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS CLI
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: us-east-1

      - name: Get Cluster Name
        id: get-cluster-name
        run: echo "CLUSTER_NAME=$(terraform output eks_cluster_name)" >> $GITHUB_ENV

      - name: Authenticate with EKS
        run: aws eks update-kubeconfig --region us-east-1 --name ${{ env.CLUSTER_NAME }}

      - name: Deploy Shipping Service
        run: kubectl apply -f k8s/shipping-service-deployment.yaml
